### ISSUE TITLE
Can't add read-only NFS picture folder

### ISSUE THREAD

**Issue by novoid** [enen92/screensaver.kaster#1]
Hi!

Thanks for your great code!

I tried to set up kaster using my pictures folder only (no Google). I've got a read-only NFS share on my file server. When I try to configure kaster ("Folder with pictures") and select to add this folder, I do get the error message "Make sure the selected folder is writable and that the new folder name is valid".

I don't know why kaster needs a writeable folder. All source code operations I could locate are for read-only access.

When I change the NFS share to be read-write-enabled, kaster accepts this picture folder.

Do you know, how I am able to use a read-only share for displaying my JPEG images?

**Comment by enen92** [comment]
Hum I need to check why it is happening. Is the folder mounted in the OS or are u using Kodi vsf (i.e. NFS:// path)?

**Comment by novoid** [comment]
Hi enen92,

I'm using RasPi3/OpenELEC (newest official) and I mounted the image folder as image folder prior to configuring kaster. Then, however, I found out that kaster asked me to add a folder by itself, not using the already mounted NFS share. So I ended up on locating and choosing the same NFS share twice.

(Note: you should mention that the user has to switch from the default screensaver to kaster in the KODI preferences. Installing kaster did not activate it automatically. Therefore, you should write a short install guide, basically a checklist, for installing and activating on KODI.)

**Comment by InuSasha** [comment]
see #2 :)

**Comment by novoid** [comment]
Thanks. I can hardly wait to get and test the patch ;-)
I sent you a remark on a minor issue of your commit.
