### ISSUE TITLE
Excessive queries to google servers?

### ISSUE THREAD

**Issue by kevinlekiller** [enen92/screensaver.kaster#18]
Hello, I installed this addon yesterday, I was just looking at pihole and noticed a massive amount of queries from the the pi with libreelec on it (~10 DNS queries per second) 270k+ queries in ~12 hours, I uninstalled the addon and the queries stopped.

(2:00 is a little while after I installed the addon, the hours of 6:00 to 9:00 kodi was playing videos)

![Screenshot_20200503_171459](https://user-images.githubusercontent.com/1641964/80926023-76f06980-8d62-11ea-9e5b-79df2e49fa5b.png)

**Comment by kevinlekiller** [comment]
I haven't done any debugging, but looking at the source ;

https://github.com/enen92/screensaver.kaster/blob/master/resources/lib/screensaver.py#L76

There should be a sleep before this continue. 

If the server continuously returns a response other than 200 (like if the server return 429 Too Many Requests for example) this will cause high CPU usage and tons of requests.

**Comment by kevinlekiller** [comment]
https://github.com/enen92/screensaver.kaster/blob/master/resources/lib/screensaver.py#L113

Changing this loop to break in a else could also save some CPU time, with default settings the for loop will loop 20,000 times, it's possible the user backs out of the screensaver near the start of the loop.

**Comment by kevinlekiller** [comment]
Not related to the issue, but adding a else with a break 2 or return here wouldn't let the for loop go all the way through to save a bit of cpu time:

https://github.com/enen92/screensaver.kaster/blob/master/resources/lib/screensaver.py#L113

**Comment by enen92** [comment]
Thanks for reporting. Should be fixed in https://github.com/enen92/screensaver.kaster/commit/2d4d63c7fc84f1f36dd345eaec95e37721fd6f6a
