### ISSUE TITLE
read-only my-pictures-folder

### ISSUE THREAD

**Issue by fuse314** [enen92/screensaver.kaster#27]
I have a network share I set to read-only for the kodi user, to display a photo show in kaster.
With the current version of Kaster, I get an error selecting this folder "this folder must be writable".
I found the following line in the settings.xml that is responsible for this error:
https://github.com/enen92/screensaver.kaster/blob/f691f5e84a3c03ba7267340c553e11c4d7e0d887/resources/settings.xml#L6

In the code, I did not find any reason for this folder to be writable. The screensaver just reads the image files (or the file "images.json", if it exists), but never writes any files.

Is it possible to change settings.xml to allow a read-only folder to be selected as a local image folder?

**Comment by enen92** [comment]
Not really as far as I remember, maybe some copy-paste from some other addon. Can you remove the writable option and test if it works on your end?

**Comment by fuse314** [comment]
yes, I removed the option="writeable" part and I can select the read-only folder.
The screensaver works as expected for me (I did not test it with a images.json file present, though).

**Comment by fuse314** [comment]
It is also working with the "images.json" present :)
